Adding some features and changes.
MarcinSz1993/roomreservations pull request #4
Opened 2023-10-15 08:29 UTC by MarcinSz1993

Done tasks.

2023-10-18 15:31 UTC, karolk92 requested changes

2023-10-18 15:31 UTC, karolk92 commented on src/main/java/com/example/roomreservations/dto/GuestDto.java
> +    public GuestDto(Long id, String name, String surname, LocalDateTime dateOfBirth, String email, String phoneNumber, List<ReservationDto> reservations) {
Data urodzenia powinna być bez czasu

2023-10-18 15:31 UTC, karolk92 commented on src/main/java/com/example/roomreservations/model/Guest.java
> +    @OneToMany(fetch = FetchType.LAZY,mappedBy = "guest", cascade = CascadeType.ALL, orphanRemoval = true)
Sprawdź czy jak usuniesz rezerwacje czy nie usuwa ci się użytkownik. Z tym Cascade jest krytyczne z której strony mapowania to użyjesz

2023-10-18 15:31 UTC, karolk92 commented on src/main/java/com/example/roomreservations/model/LoginResponse.java
> +    private final String accessToken;
Zamiast zwracać użytkownikowi token możesz użyć headera set-cookie i ustawić mu to ciastko w przeglądarce. Potem przy zapytaniu mógłbyś go wyciągać z ciastek. Taka luźna myśl ale o ciastkach warto doczytać

2023-10-18 15:31 UTC, karolk92 commented on src/main/java/com/example/roomreservations/service/ReservationService.java
> +        if(days < 1){
Co to jest 1? Wyciągnij do stałej

2023-10-18 15:31 UTC, karolk92 commented on src/main/java/com/example/roomreservations/service/ReservationService.java
>          reservation.setPrice(days * room.getPricePerNight());
Napisz metodę calculatePrice()

2023-10-22 15:49 UTC, MarcinSz1993 commented
Tasks part2.

2023-10-22 15:59 UTC, MarcinSz1993 commented on src/main/java/com/example/roomreservations/service/ReservationService.java
> +        if(days < 1){
Zmienilem logike metody bo ona była troche bez sensu, gdyż była możliwość rezerwacji pokoju od dowolnej do dowolnej godziny a tak przeciez nigdzie nie ma xD. Wiec zrobilem tak, że tylko da się na pełne doby(dni) rezerwować.

2023-10-22 16:00 UTC, MarcinSz1993 commented on src/main/java/com/example/roomreservations/service/ReservationService.java
>          reservation.setPrice(days * room.getPricePerNight());
Zmienilem logike metody bo ona była troche bez sensu, gdyż była możliwość rezerwacji pokoju od dowolnej do dowolnej godziny a tak przeciez nigdzie nie ma xD. Wiec zrobilem tak, że tylko da się na pełne doby(dni) rezerwować.

2023-10-22 16:00 UTC, MarcinSz1993 commented on src/main/java/com/example/roomreservations/model/Guest.java
> +    @OneToMany(fetch = FetchType.LAZY,mappedBy = "guest", cascade = CascadeType.ALL, orphanRemoval = true)
Sprawdziłem i użytkownik nie usuwa się z chwilą usunięcia rezerwacji.

2023-10-22 16:03 UTC, MarcinSz1993 commented on src/main/java/com/example/roomreservations/model/LoginResponse.java
> +    private final String accessToken;
Doczytałem i obejrzałem 2 filmiki na temat cookies więc troszkę już o nich wiem

2023-10-22 16:03 UTC, MarcinSz1993 commented on src/main/java/com/example/roomreservations/dto/GuestDto.java
> +    public GuestDto(Long id, String name, String surname, LocalDateTime dateOfBirth, String email, String phoneNumber, List<ReservationDto> reservations) {
Poprawione.

2023-10-31 17:04 UTC, merged